#!/bin/bash

 if [ "$#" -ne 3 ]; then 
    echo  "Error: 3 arguements required."
    exit 1
 fi

    mkdir "$1"
    touch "$1/$2.txt"
    echo "$3" > "$1/$2.txt"
    chmod 444 "$1/$2.txt"
    echo "Folder '$1' and file '$2.txt' created successfully"
